---
# tasks file for zabbix
- name: Install the Zabbix repo.
  yum:
   name: "{{zb_url_rpm}}"
   state: present
  register: zb_repo_rpm

- name: Ensure Zabbix packages are installed.
  yum:
    name: "{{zb_pkg}}"
    state: present
  when: zb_repo_rpm is changed

- name: Setup Zabbix Apache Config
  template:
    src: "./zabbix.conf.j2"
    dest: "/etc/httpd/conf.d/zabbix.conf"
    mode: 0755
  notify: restart apache
