---
# tasks file for zabbix
- name: Install the Zabbix repo.
  apt:
   deb: "{{zb_url_deb}}"
  register: zb_repo_deb

- name: Ensure Zabbix packages are installed.
  apt:
    name: "{{ zb_pkg }}"
    state: present
  when: zb_repo_deb is changed

- name: Setup Zabbix Apache Config
  template:
    src: "./zabbix.conf.j2"
    dest: "/etc/apache2/conf-enabled/zabbix.conf"
    mode: 0755
  notify: restart apache
